- agent:
    name: "sorter"
    system_prompt:
      role: system
      content: "You are an executive at a news broadcasting company.  Your job is to assess a list of news headlines, and decide which is the best headline, based on importance and timeliness, in each of three categories: international (non-sports news), domestic (non-sports news), and sports (domestic and international sports news).  Each headline will be shared with a specialist for that category."
    few_shot_prompt:
      - role: user
        content: >
          Here are the headlines:

          index: 1
          title: Russia says Wagner Group's leader will move to Belarus after his rebellious march challenged Putin
          link: https://www.bbc.co.uk/news/business-65997926?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 23:04:45 GMT

          index: 2
          title: Israeli military kills Palestinian gunman as settlers rampage through Palestinian town

          link: https://www.bbc.co.uk/news/world-africa-65947114?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 23:15:54 GMT

          index: 3
          title: Migrant deaths: Four players suspended after hostile soccer game between US and Mexico
          link: https://www.bbc.co.uk/news/world-latin-america-65932680?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 00:10:37 GMT

          index: 4
          title: The ultra-wealthy have dangerous pastimes. Who pays when they need saving?
          link: https://www.bbc.co.uk/news/business-65997926?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 23:04:45 GMT

          index: 5
          title: Zimbabwe's obsession with Animal Farm as novel gets Shona translation
          link: https://www.bbc.co.uk/news/world-africa-65947114?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 23:15:54 GMT

          index: 6
          title: Speaker McCarthy supports expunging Trump's impeachments over Ukraine and Jan. 6
          link: https://www.bbc.co.uk/news/world-latin-america-65932680?at_medium=RSS&at_campaign=KARANGA
          published: Sat, 24 Jun 2023 00:10:37 GMT
      - role: assistant
        content: None
        function_call:
          name: sort_headlines
          arguments: >
            [
              {
                "specialist": "International", 
                "headline": "Russia says Wagner Group's leader will move to Belarus after his rebellious march challenged Putin"
                "index": 1
              },
              {
                "specialist": "Sports",
                "headline": "Four players suspended after hostile soccer game between US and Mexico"
                "index": 3
              },
              {
                "specialist": "Domestic",
                "headline": "Speaker McCarthy supports expunging Trump's impeachments over Ukraine and Jan. 6"
                "index": 6
              }
            ]

- function:
    name: "sort_headlines"
    description: "Given a list of news headlines, decide which specialists will evaluate the news item."
    parameters:
      type: "object"
      properties:
        specialist:
          type: "string"
          description: "specialist type"
        headline:
          type: "string"
          description: "headline"
        index:
          type: "integer"
          description: "index of the headline"
      required:
        - "specialist"
        - "headline"
        - "index"
